package ru.example.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

public class StudentDbUtil {

    private static StudentDbUtil instance;
    private static final Logger log;

    static {
        log = Logger.getLogger(StudentDbUtil.class.getName());
    }

    public static StudentDbUtil getInstance() {
        if (instance == null) {
            instance = new StudentDbUtil();
        }
        return instance;
    }

    private StudentDbUtil() {
        final Connection connection;
        try {
            connection = DataSource.getConnection();
            connection.setAutoCommit(true);
            final Statement statement = connection.createStatement();
            log.info("INF:Create table..");
            statement.execute("CREATE TABLE student(\n" +
                    "                        id         int NOT NULL generated by default as identity,\n" +
                    "                        first_name varchar(45) DEFAULT NULL,\n" +
                    "                        last_name  varchar(45) DEFAULT NULL,\n" +
                    "                        email      varchar(45) DEFAULT NULL,\n" +
                    "                        PRIMARY KEY (id)\n" +
                    ")");

            statement.execute("INSERT INTO student VALUES (1, 'Mary', 'Public', 'mary@luv2code.com')");
            statement.execute("INSERT INTO student VALUES (2, 'John', 'Doe', 'john@luv2code.com')");
            statement.execute("INSERT INTO student VALUES (3, 'Ajay', 'Rao', 'ajay@luv2code.com')");
            statement.execute("INSERT INTO student VALUES (4, 'Bill', 'Neely', 'bill@luv2code.com')");
            statement.execute("INSERT INTO student VALUES (5, 'Maxwell', 'Dixon', 'max@luv2code.com')");
            close(connection, statement);
        } catch (SQLException e) {
            log.warning("EX:" + e.getMessage());
            e.printStackTrace();
        }
    }

    public static void close(Connection connection, Statement statement) {
        close(connection, statement, null);
    }

    private static void close(Connection connection, Statement statement, ResultSet resultSet) {
        try {
            if (resultSet != null) {
                resultSet.close();
            }
            if (statement != null) {
                statement.close();
            }
            if (connection != null) {
                connection.close();
            }
        } catch (SQLException e) {
            log.warning("EX:" + e.getMessage());

        }
    }

    public List<Student> getStudents() throws SQLException {

        final List<Student> students = new ArrayList<>();
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        try {
            connection = DataSource.getConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery("SELECT * FROM student");
            while (resultSet.next()) {
                final int id = resultSet.getInt("id");
                final String firstName = resultSet.getString("first_name");
                final String lastName = resultSet.getString("last_name");
                final String email = resultSet.getString("email");
                students.add(new Student(id, firstName, lastName, email));
            }
        } finally {
            close(connection,statement,resultSet);
        }
        return students;
    }
//
//    public Student getStudent() {
//
//    }
//
//    public Student addStudent() {
//
//    }
//
//    public Student updateStudent() {
//
//    }
//
//    public void deleteStudent() {
//
//    }
}
